language: node_js

node_js:
  - 6
  - 8

services:
  - redis-server

before_install:
  - rvm install 2.5.0

script:
  - bundle exec rake spec
  - grunt spec

after_success:
  - bundle exec codeclimate-test-reporter
